@startuml
title 簽核狀態圖

state 待審 {
  [*] --> 待簽
  待簽 --> 暫批
  暫批 --> 同意
  暫批--> 不同意
  待簽 -left-> 知悉
  待簽 --> 同意
  待簽 --> 不同意
  知悉--> [*]
  同意--> [*]
  不同意--> [*]
}

[*] -down-> 申請
申請 -left-> 取消
申請 -down-> 待審
待審 -up-> 申請 
待審 -down-> 完成
待審 -down-> 拒絕
取消 -down-> [*]
拒絕 -down-> [*]
完成 -down-> [*]
@enduml