@startuml
class 廠商資訊 {
    廠商主檔
    聯絡人
}

class 常備品合約 {
    物品主檔
    合約起始日期
    合約結束日期
    採購單價
}

物品分類 --> 物品分類
物品分類 "1" -up- "*" 會計科目
物品分類 "1" -up- "*" 採購承辦人
物品分類 "1" -up- "*" 流程簽核人
物品分類 "1" -- "*" 物品主檔
標準名稱 --> 標準名稱
物品分類 "1" -- "*" 標準名稱
標準名稱 "1" -- "*" 物品主檔
物品主檔 <|-- 資產.資產主檔
物品主檔 "1" *-right- "*" 證照
物品主檔 *-- UOM.單位
物品主檔 "1" *-left- "*" 廠商資訊
廠商資訊 o-left- 廠商主檔
廠商主檔 "1" *-- "*" 承辦人
廠商主檔 *-up- 常備品合約
廠商主檔 *-- 付款條件

電話簿.聯絡人 <|-- 承辦人
@enduml