@startuml

class 資源借用 #MistyRose
class 開會通知 #MistyRose
class 會議記錄 #MistyRose
class 資源權限 {
    單位
}
class 借用資源  {
    借用時間
    歸還時間
    狀態
}

資源主檔 "1" *-- "*" 設備項目
資源主檔 "1" *-- "*" 資源權限

資源借用 "1" -right- "*" 借用資源
借用資源  *-right- 資源主檔

開會通知 .up.> 行事曆.日曆
開會通知 o-right- 資源借用
開會通知 *-right- 會議代碼
開會通知 "1" -- "*" 與會人員
開會通知 "1" -- "*" 信件副本
開會通知 "1" -- "*" 密件副本
開會通知 <|-left- 會議記錄
流程.流程表單 <|-- 會議記錄
會議記錄 "1" *-- "*" 待辦事項

@enduml